// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd8igXxDBrHY6pCGeD5f0G8ahLtvJhYow',
    appId: '1:607107855897:web:14d1232f36aff11182dc88',
    messagingSenderId: '607107855897',
    projectId: 'chatapp-95825',
    authDomain: 'chatapp-95825.firebaseapp.com',
    storageBucket: 'chatapp-95825.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_D5v1bBEiIuNr07CAKY4iPf_9kqOLQFA',
    appId: '1:607107855897:android:09e02fffe7ceccfa82dc88',
    messagingSenderId: '607107855897',
    projectId: 'chatapp-95825',
    storageBucket: 'chatapp-95825.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB4A8hylaKXrqzk48ZnBui8_UBnzaOQL8',
    appId: '1:607107855897:ios:0466fd7740d7863482dc88',
    messagingSenderId: '607107855897',
    projectId: 'chatapp-95825',
    storageBucket: 'chatapp-95825.firebasestorage.app',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB4A8hylaKXrqzk48ZnBui8_UBnzaOQL8',
    appId: '1:607107855897:ios:0466fd7740d7863482dc88',
    messagingSenderId: '607107855897',
    projectId: 'chatapp-95825',
    storageBucket: 'chatapp-95825.firebasestorage.app',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAd8igXxDBrHY6pCGeD5f0G8ahLtvJhYow',
    appId: '1:607107855897:web:07f4b14c77f0b9b682dc88',
    messagingSenderId: '607107855897',
    projectId: 'chatapp-95825',
    authDomain: 'chatapp-95825.firebaseapp.com',
    storageBucket: 'chatapp-95825.firebasestorage.app',
  );

}